name: Build-pack

on: 
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-pack:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - run: echo "$(cat test.txt)"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore src/Commergent.Dw.DemoApp.sln

      - name: Build
        run: dotnet build src/Commergent.Dw.DemoApp.sln -c Release --no-restore /p:Version=${PACKAGE_VERSION}

      - name: Pack
        run: |
          dotnet pack src/Commergent.Dw.DemoApp.csproj \
            -c Release \
            /p:PackageVersion=${PACKAGE_VERSION} \
            /p:Version=${PACKAGE_VERSION} \
            -o ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate

      - name: Check AZURE_DEVOPS_PAT present
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          if [ -z "$AZURE_DEVOPS_PAT" ]; then
            echo "AZURE_DEVOPS_PAT is empty!"
            exit 1
          else
            echo "AZURE_DEVOPS_PAT is set (hidden)."
          fi

      - name: Configure Azure Artifacts source
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          dotnet nuget add source "https://pkgs.dev.azure.com/commergent/InternalPackages/_packaging/MainFeed/nuget/v3/index.json" \
            --name "MainFeed" \
            --username "anything" \
            --password "$AZURE_DEVOPS_PAT" \
            --store-password-in-clear-text

      - name: Publish to Azure Artifacts
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source "MainFeed" \
            --api-key "Anything" \
            --skip-duplicate
