name: Build-pack

on: 
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-pack:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - run: echo "$(cat test.txt)"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore src/Commergent.Dw.DemoApp.sln

      - name: Build
        run: dotnet build src/Commergent.Dw.DemoApp.sln -c Release --no-restore

      - name: Pack
        run: dotnet pack src/Commergent.Dw.DemoApp.csproj -c Release --no-build -o ./artifacts /p:PackageVersion=${PACKAGE_VERSION}

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate

      - name: Publish to Azure Artifacts
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://pkgs.dev.azure.com/commergent/InternalPackages/_packaging/MainFeed/nuget/v3/index.json" --api-key "$AZURE_DEVOPS_PAT" --skip-duplicate
      
